#This is the sage code verifying the claim in Section 4 of the paper "Triple intersection for algebraic curves on the real torus"
#Given the polinomials g_0,g_1,g_2 with coefficients in Q[a,b,c,d,e,f], we determine equations for the locus of teh parameters a,b,c,d,e,f for which the three quadrics are linearly dependent. 
#The coefficients of g_0, g_1, g_2 are arranged in the columns of a 3 x 11 matrix M. The three quadrics are linearly dependent if and only if M has rank at most 2, which is equivalent to the vanishing of all its 3 x 3 minors. Therefore, we compute the ideal generated by all 3 x 3 minors of M and then determine its Groebner basis. 


R.<a,b,c,d,e,f> = PolynomialRing(QQ, order='deglex')

# Vettori of coefficients. The components of the vector vXY are the coefficients of the monomial XY in the polynomials g_0,g_1,g_2 respectively

vm1m1 = vector(R, [a^3*c*d^2-2*a*b*c*d^2+c^2*d^2+2*b*c*d*e+a*c*e^2-2*a^2*c*d*e+2*a*c*d*f-2*c*e*f, a^3*b*d^2-2*a*b^2*d^2-a^2*c*d^2-2*a^2*b*d*e+2*b*c*d^2+2*b^2*d*e+2*a*c*d*e+a*b*e^2+2*a*b*d*f-c*e^2-2*c*d*f-2*b*e*f, a^4*d^2-3*a^2*b*d^2-2*a^3*d*e+2*a*c*d^2+ b^2*d^2+4*a*b*d*e+a^2*e^2+2*a^2*d*f-2*c*d*e-b*e^2-2*b*d*f-2*a*e*f+f^2+1])

vm2m2 =vector(R, [a^3*c*d^2-2*a*b*c*d^2+a*c*d^2+2*a*c*d*f-2*a^2*c*d*e+c^2*d^2+2*b*c*d*e+a*c*e^2-2*c*d*e-2*c*e*f+f^2, a^3*b*d^2-2*a*b^2*d^2-a^2*c*d^2-2*a^2*b*d*e+a*b*d^2+2*b*c*d^2+2*a*b*d*f+2*b^2*d*e+2*a*c*d*e+a*b*e^2-c*d^2-2*b*e*f-2*b*d*e-c*e^2+2*e*f-2*c*d*f, a^4*d^2 -3*a^2*b*d^2-2*a^3*d*e+b^2*d^2+a^2*d^2+2*a*c*d^2+a^2*e^2+4*a*b*d*e-b*d^2+2*a^2*d*f-2*a*d*e+ -2*c*d*e-b*e^2-2*b*d*f-2*a*e*f+e^2+2*d*f+f^2])

vm1m2 =vector(R, [-a^3*c*d^2+2*a*b*c*d^2+2*a^2*c*d*e-c^2*d^2-2*b*c*d*e-2*a*c*e^2-2*a*c*d*f+2*c*d+4*c*e*f,4*a*b^2*d^2-2*a^3*b*d^2+2*a^2*c*d^2+4*a^2*b*d*e-4*b*c*d^2-4*b^2*d*e-4*a*c*d*e-2*a*b*e^2-4*a*b*d*f+2*c*e^2+2*b*d+4*c*d*f-2*f*+ 4*b*e*f,6*a^2*b*d^2-2*a^4*d^2+4*a^3*d*e-2*b^2*d^2-4*a*c*d^2-8*a*b*d*e-2*a^2*e^2-4*a^2*d*f+ 4*c*d*e+2*b*e^2+4*b*d*f+4*a*e*f+2*a*d-2*f^2-2*e])

vm1n1 =vector(R, [-2*a*c*d*e-b*c*d^2+a^2*c*d^2+c*e^2+2*c*d*f, -b^2*d^2-2*a*b*d*e+a^2*b*d^2-a*c*d^2+2*c*d*e+b*e^2+2*b*d*f-f^2-2, -2*a*b*d^2-2*a^2*d*e+a^3*d^2+c*d^2+2*b*d*e+a*e^2+2*a*d*f-2*e*f])

vm1n2 =vector(R, [a*c*d-c*e, a*b*d-c*d-b*e+1, a^2*d-b*d-a*e+f])

vm2n1 =vector(R, [2*a*c*d*e-a^2*c*d^2+b*c*d^2-c*e^2-2*c*d*f+f, b^2*d^2+2*a*b*d*e+a*c*d^2-2*c*d*e-a^2*b*d^2-b*e^2-2*b*d*f+f^2+e, 2*a^2*d*e+2*a*b*d^2-a^3*d^2-c*d^2-2*b*d*e-2*a*d*f-a*e^2+2*e*f+d])

vm2n2 =vector(R, [c*e-a*c*d-f, -a*b*d+c*d+b*e-e, -a^2*d+b*d+a*e-d-f])

vn1n1 = vector(R,[a*c*d^2-2*c*d*e+f^2+1,a*b*d^2-c*d^2-2*b*d*e+2*e*f,a^2*d^2-b*d^2-2*a*d*e+e^2+2*d*f])

vn2n2 =vector(R, [1, 0, 1])

vn1n2 = vector(R, [c*d-1,-f+b*d,a*d-e])

v1 = vector(R, [-f^2-a*c*d^2-2*c*d+2*c*d*e,-2*e*f+2*f-a*b*d^2+c*d^2+2*b*d*e-2*b*d,-e^2-2*d*f+2*e-1-a^2*d^2+2*a*d*e+b*d^2-2*a*d])


Mt = matrix(R, 11, 3, [vm1m1,vm2m2,vm1m2,vn1n1,vn2n2,vn1n2,vm1n1,vm1n2,vm2n1,vm2n2,v1])
M = Mt.transpose()

#Here we compute the ideal I generated by the determinants of the 3x3 minors
dets = [];
for cols in Subsets(range(11), 3):
    minor = M.matrix_from_columns(list(cols))  
    dets.append(minor.det())           
I = ideal(dets)


GB = I.groebner_basis()
show(GB)